# -- Window and layer rules -- #

# -- Window rules

# Ignore maximize requests
windowrule = match:class .*, suppress_event maximize

# Remove the right-click menu blurring in Chromium browsers
windowrule = match:class ^$, match:title ^$, no_blur on

# Remove the weird pop-up behavior in VSCode
#windowrule = match:class ^(codium)$, stay_focused on
windowrule = match:class ^(codium)$, min_size 1 1

# Make file picker windows floating
windowrule = match:title ^(Open File|Open|Save|Save As|Export|Import|Choose File|Rename|script-fu), match:class ^(.*)$, float on, center on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on, center on
windowrule = match:class ^(xdg-desktop-portal-hyprland)$, float on, center on
windowrule = match:class ^(Xdg-desktop-portal-gtk)$, float on, center on
windowrule = match:class ^(Xdg-desktop-portal-hyprland)$, float on, center on
windowrule = match:class ^(Xdg-desktop-portal-gtk)$, border_size 0

# Disable borders for swaync
windowrule = match:class ^(swaync)$, border_size 0

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

# Make browsers opaque
#windowrule = match:class ^(zen|librewolf|firefox|brave)$, opacity 1.0 override

#Pulsecontrol
windowrule = match:class ^(org\.test\.pulsecontrol)$, float on, center on, size 800 650

#Blueman-Manger
windowrule = match:class ^(blueman-manager)$, float on, center on, size 800 500


#--------Layer Rules-------

# Blur Waybar
# Note: Combining ignorezero and ignorealpha into a single rule. ignore_alpha 0.5 covers it.
layerrule = match:namespace waybar, blur on, ignore_alpha 0.5

# Blur swaync
layerrule = match:namespace swaync-control-center, blur on, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, blur on, ignore_alpha 0.5

# Blur wlogout
layerrule = match:namespace logout_dialog, blur on

# Rofi
#layerrule = match:namespace rofi, dim_around on
layerrule = match:namespace rofi, blur on, ignore_alpha 0.5, animation popin 95%
