cursor            #68f0f0
cursor_text_color #002b2b

foreground            #ffffff
background            #03080f
selection_foreground  #002b2b
selection_background  #96ebea
url_color             #96ebea

#: black 000000 767676
color0  #0c141b
color8  #373e47
#: red cc0403 f2201f
color1  #ffd2cc
color9  #ffffff
#: green 19cb00 23fd00
color2  #80d5d4
color10 #9cf1f0
#: yellow cecb00 fffd00
color3  #9accfa
color11 #cde5ff
#: blue 0d73cc 1a8fff
color4  #003d3d
color12 #68f0f0
#: magenta cb1ed1 fd28ff
color5  #003d3d
color13 #96ebea
#: cyan 0dcdcd 14ffff
color6  #00395b
color14 #c1e0ff
#: white dddddd ffffff
color7  #cedef0
color15 #ffffff

mark1_foreground #001414
mark1_background #6ff7f6
mark2_foreground #001414
mark2_background #9cf1f0
mark3_foreground #001322
mark3_background #cde5ff

active_tab_foreground #002b2b
active_tab_background #68f0f0
inactive_tab_foreground #000000
inactive_tab_background #00a1a1

active_border_color #68f0f0
inactive_border_color #002b2b
# bell_border_color #ff5a00