$image = /home/christoforos/Pictures/Wallpapers/wallhaven-lywevp.jpg

$background = rgba(0c141bff)

$error = rgba(ffd2ccff)

$error_container = rgba(ff5449ff)

$inverse_on_surface = rgba(232b32ff)

$inverse_primary = rgba(005151ff)

$inverse_surface = rgba(dce3edff)

$on_background = rgba(dce3edff)

$on_error = rgba(540003ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(002b2bff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(001414ff)

$on_primary_fixed_variant = rgba(003d3dff)

$on_secondary = rgba(002b2bff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(001414ff)

$on_secondary_fixed_variant = rgba(003d3dff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(cedef0ff)

$on_tertiary = rgba(002841ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(001322ff)

$on_tertiary_fixed_variant = rgba(00395bff)

$outline = rgba(a4b4c5ff)

$outline_variant = rgba(8392a2ff)

$primary = rgba(68f0f0ff)

$primary_container = rgba(00a1a1ff)

$primary_fixed = rgba(6ff7f6ff)

$primary_fixed_dim = rgba(4cdadaff)

$scrim = rgba(000000ff)

$secondary = rgba(96ebeaff)

$secondary_container = rgba(479e9eff)

$secondary_fixed = rgba(9cf1f0ff)

$secondary_fixed_dim = rgba(80d5d4ff)

$shadow = rgba(000000ff)

$source_color = rgba(0f1419ff)

$surface = rgba(0c141bff)

$surface_bright = rgba(3e454dff)

$surface_container = rgba(212930ff)

$surface_container_high = rgba(2c333bff)

$surface_container_highest = rgba(373e47ff)

$surface_container_low = rgba(171e26ff)

$surface_container_lowest = rgba(03080fff)

$surface_dim = rgba(0c141bff)

$surface_tint = rgba(4cdadaff)

$surface_variant = rgba(394857ff)

$tertiary = rgba(c1e0ffff)

$tertiary_container = rgba(6395c1ff)

$tertiary_fixed = rgba(cde5ffff)

$tertiary_fixed_dim = rgba(9accfaff)

