$image = /home/christoforos/.config/colorschemes/matugen/wallpapers/nebula.jpg

$background = rgba(1c1015ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(3b2c32ff)

$inverse_primary = rgba(b70071ff)

$inverse_surface = rgba(f5dce3ff)

$on_background = rgba(f5dce3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(63003bff)

$on_primary_container = rgba(ffd9e5ff)

$on_primary_fixed = rgba(3d0023ff)

$on_primary_fixed_variant = rgba(8c0055ff)

$on_secondary = rgba(4b252dff)

$on_secondary_container = rgba(ffd9deff)

$on_secondary_fixed = rgba(321018ff)

$on_secondary_fixed_variant = rgba(653b43ff)

$on_surface = rgba(f5dce3ff)

$on_surface_variant = rgba(d8c1c7ff)

$on_tertiary = rgba(532020ff)

$on_tertiary_container = rgba(ffdad8ff)

$on_tertiary_fixed = rgba(380b0dff)

$on_tertiary_fixed_variant = rgba(6f3635ff)

$outline = rgba(a08b92ff)

$outline_variant = rgba(534248ff)

$primary = rgba(ffb0cfff)

$primary_container = rgba(8c0055ff)

$primary_fixed = rgba(ffd9e5ff)

$primary_fixed_dim = rgba(ffb0cfff)

$scrim = rgba(000000ff)

$secondary = rgba(f2b7c1ff)

$secondary_container = rgba(653b43ff)

$secondary_fixed = rgba(ffd9deff)

$secondary_fixed_dim = rgba(f2b7c1ff)

$shadow = rgba(000000ff)

$source_color = rgba(eb509eff)

$surface = rgba(1c1015ff)

$surface_bright = rgba(44353aff)

$surface_container = rgba(291c21ff)

$surface_container_high = rgba(34262bff)

$surface_container_highest = rgba(403136ff)

$surface_container_low = rgba(25181dff)

$surface_container_lowest = rgba(160b0fff)

$surface_dim = rgba(1c1015ff)

$surface_tint = rgba(ffb0cfff)

$surface_variant = rgba(534248ff)

$tertiary = rgba(ffb3b0ff)

$tertiary_container = rgba(6f3635ff)

$tertiary_fixed = rgba(ffdad8ff)

$tertiary_fixed_dim = rgba(ffb3b0ff)

