$image = /home/christoforos/.config/colorschemes/matugen/wallpapers/wallhaven-l8p93p.png

$background = rgba(091516ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(263334ff)

$inverse_primary = rgba(00696fff)

$inverse_surface = rgba(d7e5e6ff)

$on_background = rgba(d7e5e6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(00363aff)

$on_primary_container = rgba(77f5ffff)

$on_primary_fixed = rgba(002022ff)

$on_primary_fixed_variant = rgba(004f54ff)

$on_secondary = rgba(043542ff)

$on_secondary_container = rgba(bfe9f9ff)

$on_secondary_fixed = rgba(001f28ff)

$on_secondary_fixed_variant = rgba(224c59ff)

$on_surface = rgba(d7e5e6ff)

$on_surface_variant = rgba(bbc9caff)

$on_tertiary = rgba(00344cff)

$on_tertiary_container = rgba(c7e7ffff)

$on_tertiary_fixed = rgba(001e2eff)

$on_tertiary_fixed_variant = rgba(114b69ff)

$outline = rgba(869394ff)

$outline_variant = rgba(3c494aff)

$primary = rgba(00dbe8ff)

$primary_container = rgba(004f54ff)

$primary_fixed = rgba(77f5ffff)

$primary_fixed_dim = rgba(00dbe8ff)

$scrim = rgba(000000ff)

$secondary = rgba(a4cddcff)

$secondary_container = rgba(224c59ff)

$secondary_fixed = rgba(bfe9f9ff)

$secondary_fixed_dim = rgba(a4cddcff)

$shadow = rgba(000000ff)

$source_color = rgba(2e5e62ff)

$surface = rgba(091516ff)

$surface_bright = rgba(2f3b3dff)

$surface_container = rgba(152223ff)

$surface_container_high = rgba(202c2dff)

$surface_container_highest = rgba(2a3738ff)

$surface_container_low = rgba(111e1fff)

$surface_container_lowest = rgba(041011ff)

$surface_dim = rgba(091516ff)

$surface_tint = rgba(00dbe8ff)

$surface_variant = rgba(3c494aff)

$tertiary = rgba(9bcdf0ff)

$tertiary_container = rgba(114b69ff)

$tertiary_fixed = rgba(c7e7ffff)

$tertiary_fixed_dim = rgba(9bcdf0ff)

