.pragma library

// GENERATED -- see scratchpad/gen_pickers.py in the session that
// created it. Hand edits are fine; regenerating overwrites them.

// Codepoints with Unicode's Emoji_Presentation property, i.e. the
// ones that render as color emoji by default. Everything else that
// used to live in the launcher's ':' mode moved to Glyphs.js.

var list = [
    { e: "⌚", n: "watch" },
    { e: "⌛", n: "hourglass", k: "wait time hourglass" },
    { e: "⏩", n: "black right-pointing double triangle" },
    { e: "⏪", n: "black left-pointing double triangle" },
    { e: "⏫", n: "black up-pointing double triangle" },
    { e: "⏬", n: "black down-pointing double triangle" },
    { e: "⏰", n: "alarm clock", k: "time wake alarm clock" },
    { e: "⏳", n: "hourglass with flowing sand", k: "wait loading hourglass" },
    { e: "🌀", n: "cyclone" },
    { e: "🌁", n: "foggy" },
    { e: "🌂", n: "closed umbrella" },
    { e: "🌃", n: "night with stars" },
    { e: "🌄", n: "sunrise over mountains" },
    { e: "🌅", n: "sunrise" },
    { e: "🌆", n: "cityscape at dusk" },
    { e: "🌇", n: "sunset over buildings" },
    { e: "🌈", n: "rainbow" },
    { e: "🌉", n: "bridge at night" },
    { e: "🌊", n: "water wave" },
    { e: "🌋", n: "volcano" },
    { e: "🌌", n: "milky way" },
    { e: "🌍", n: "earth globe europe-africa" },
    { e: "🌎", n: "earth globe americas" },
    { e: "🌏", n: "earth globe asia-australia" },
    { e: "🌐", n: "globe with meridians" },
    { e: "🌑", n: "new moon symbol" },
    { e: "🌒", n: "waxing crescent moon symbol" },
    { e: "🌓", n: "first quarter moon symbol" },
    { e: "🌔", n: "waxing gibbous moon symbol" },
    { e: "🌕", n: "full moon symbol" },
    { e: "🌖", n: "waning gibbous moon symbol" },
    { e: "🌗", n: "last quarter moon symbol" },
    { e: "🌘", n: "waning crescent moon symbol" },
    { e: "🌙", n: "crescent moon" },
    { e: "🌚", n: "new moon with face" },
    { e: "🌛", n: "first quarter moon with face" },
    { e: "🌜", n: "last quarter moon with face" },
    { e: "🌝", n: "full moon with face" },
    { e: "🌞", n: "sun with face" },
    { e: "🌟", n: "glowing star" },
    { e: "🌠", n: "shooting star" },
    { e: "🌭", n: "hot dog" },
    { e: "🌮", n: "taco" },
    { e: "🌯", n: "burrito" },
    { e: "🌰", n: "chestnut" },
    { e: "🌱", n: "seedling" },
    { e: "🌲", n: "evergreen tree" },
    { e: "🌳", n: "deciduous tree" },
    { e: "🌴", n: "palm tree" },
    { e: "🌵", n: "cactus" },
    { e: "🌷", n: "tulip" },
    { e: "🌸", n: "cherry blossom" },
    { e: "🌹", n: "rose" },
    { e: "🌺", n: "hibiscus" },
    { e: "🌻", n: "sunflower" },
    { e: "🌼", n: "blossom" },
    { e: "🌽", n: "ear of maize" },
    { e: "🌾", n: "ear of rice" },
    { e: "🌿", n: "herb" },
    { e: "🍀", n: "four leaf clover" },
    { e: "🍁", n: "maple leaf" },
    { e: "🍂", n: "fallen leaf" },
    { e: "🍃", n: "leaf fluttering in wind" },
    { e: "🍄", n: "mushroom" },
    { e: "🍅", n: "tomato" },
    { e: "🍆", n: "aubergine" },
    { e: "🍇", n: "grapes" },
    { e: "🍈", n: "melon" },
    { e: "🍉", n: "watermelon" },
    { e: "🍊", n: "tangerine" },
    { e: "🍋", n: "lemon" },
    { e: "🍌", n: "banana" },
    { e: "🍍", n: "pineapple" },
    { e: "🍎", n: "red apple" },
    { e: "🍏", n: "green apple" },
    { e: "🍐", n: "pear" },
    { e: "🍑", n: "peach" },
    { e: "🍒", n: "cherries" },
    { e: "🍓", n: "strawberry" },
    { e: "🍔", n: "hamburger" },
    { e: "🍕", n: "slice of pizza", k: "pizza food" },
    { e: "🍖", n: "meat on bone" },
    { e: "🍗", n: "poultry leg" },
    { e: "🍘", n: "rice cracker" },
    { e: "🍙", n: "rice ball" },
    { e: "🍚", n: "cooked rice" },
    { e: "🍛", n: "curry and rice" },
    { e: "🍜", n: "steaming bowl" },
    { e: "🍝", n: "spaghetti" },
    { e: "🍞", n: "bread" },
    { e: "🍟", n: "french fries" },
    { e: "🍠", n: "roasted sweet potato" },
    { e: "🍡", n: "dango" },
    { e: "🍢", n: "oden" },
    { e: "🍣", n: "sushi" },
    { e: "🍤", n: "fried shrimp" },
    { e: "🍥", n: "fish cake with swirl design" },
    { e: "🍦", n: "soft ice cream" },
    { e: "🍧", n: "shaved ice" },
    { e: "🍨", n: "ice cream" },
    { e: "🍩", n: "doughnut" },
    { e: "🍪", n: "cookie" },
    { e: "🍫", n: "chocolate bar" },
    { e: "🍬", n: "candy" },
    { e: "🍭", n: "lollipop" },
    { e: "🍮", n: "custard" },
    { e: "🍯", n: "honey pot" },
    { e: "🍰", n: "shortcake" },
    { e: "🍱", n: "bento box" },
    { e: "🍲", n: "pot of food" },
    { e: "🍳", n: "cooking" },
    { e: "🍴", n: "fork and knife" },
    { e: "🍵", n: "teacup without handle" },
    { e: "🍶", n: "sake bottle and cup" },
    { e: "🍷", n: "wine glass" },
    { e: "🍸", n: "cocktail glass" },
    { e: "🍹", n: "tropical drink" },
    { e: "🍺", n: "beer mug", k: "beer drink pub" },
    { e: "🍻", n: "clinking beer mugs" },
    { e: "🍼", n: "baby bottle" },
    { e: "🍾", n: "bottle with popping cork" },
    { e: "🍿", n: "popcorn" },
    { e: "🎀", n: "ribbon" },
    { e: "🎁", n: "wrapped present" },
    { e: "🎂", n: "birthday cake", k: "bday birthday cake party" },
    { e: "🎃", n: "jack-o-lantern" },
    { e: "🎄", n: "christmas tree" },
    { e: "🎅", n: "father christmas" },
    { e: "🎆", n: "fireworks" },
    { e: "🎇", n: "firework sparkler" },
    { e: "🎈", n: "balloon" },
    { e: "🎉", n: "party popper", k: "party celebrate tada yay" },
    { e: "🎊", n: "confetti ball", k: "party celebrate" },
    { e: "🎋", n: "tanabata tree" },
    { e: "🎌", n: "crossed flags" },
    { e: "🎍", n: "pine decoration" },
    { e: "🎎", n: "japanese dolls" },
    { e: "🎏", n: "carp streamer" },
    { e: "🎐", n: "wind chime" },
    { e: "🎑", n: "moon viewing ceremony" },
    { e: "🎒", n: "school satchel" },
    { e: "🎓", n: "graduation cap" },
    { e: "🎠", n: "carousel horse" },
    { e: "🎡", n: "ferris wheel" },
    { e: "🎢", n: "roller coaster" },
    { e: "🎣", n: "fishing pole and fish" },
    { e: "🎤", n: "microphone" },
    { e: "🎥", n: "movie camera" },
    { e: "🎦", n: "cinema" },
    { e: "🎧", n: "headphone" },
    { e: "🎨", n: "artist palette" },
    { e: "🎩", n: "top hat" },
    { e: "🎪", n: "circus tent" },
    { e: "🎫", n: "ticket" },
    { e: "🎬", n: "clapper board" },
    { e: "🎭", n: "performing arts" },
    { e: "🎮", n: "video game" },
    { e: "🎯", n: "direct hit", k: "target goal bullseye" },
    { e: "🎰", n: "slot machine" },
    { e: "🎱", n: "billiards" },
    { e: "🎲", n: "game die" },
    { e: "🎳", n: "bowling" },
    { e: "🎴", n: "flower playing cards" },
    { e: "🎵", n: "musical note" },
    { e: "🎶", n: "multiple musical notes" },
    { e: "🎷", n: "saxophone" },
    { e: "🎸", n: "guitar" },
    { e: "🎹", n: "musical keyboard" },
    { e: "🎺", n: "trumpet" },
    { e: "🎻", n: "violin" },
    { e: "🎼", n: "musical score" },
    { e: "🎽", n: "running shirt with sash" },
    { e: "🎾", n: "tennis racquet and ball" },
    { e: "🎿", n: "ski and ski boot" },
    { e: "🏀", n: "basketball and hoop" },
    { e: "🏁", n: "chequered flag" },
    { e: "🏂", n: "snowboarder" },
    { e: "🏃", n: "runner" },
    { e: "🏄", n: "surfer" },
    { e: "🏅", n: "sports medal" },
    { e: "🏆", n: "trophy", k: "win trophy award" },
    { e: "🏇", n: "horse racing" },
    { e: "🏈", n: "american football" },
    { e: "🏉", n: "rugby football" },
    { e: "🏊", n: "swimmer" },
    { e: "🏏", n: "cricket bat and ball" },
    { e: "🏐", n: "volleyball" },
    { e: "🏑", n: "field hockey stick and ball" },
    { e: "🏒", n: "ice hockey stick and puck" },
    { e: "🏓", n: "table tennis paddle and ball" },
    { e: "🏠", n: "house building" },
    { e: "🏡", n: "house with garden" },
    { e: "🏢", n: "office building" },
    { e: "🏣", n: "japanese post office" },
    { e: "🏤", n: "european post office" },
    { e: "🏥", n: "hospital" },
    { e: "🏦", n: "bank" },
    { e: "🏧", n: "automated teller machine" },
    { e: "🏨", n: "hotel" },
    { e: "🏩", n: "love hotel" },
    { e: "🏪", n: "convenience store" },
    { e: "🏫", n: "school" },
    { e: "🏬", n: "department store" },
    { e: "🏭", n: "factory" },
    { e: "🏮", n: "izakaya lantern" },
    { e: "🏯", n: "japanese castle" },
    { e: "🏰", n: "european castle" },
    { e: "🏴", n: "waving black flag" },
    { e: "🏸", n: "badminton racquet and shuttlecock" },
    { e: "🏹", n: "bow and arrow" },
    { e: "🏺", n: "amphora" },
    { e: "🏻", n: "emoji modifier fitzpatrick type-1-2" },
    { e: "🏼", n: "emoji modifier fitzpatrick type-3" },
    { e: "🏽", n: "emoji modifier fitzpatrick type-4" },
    { e: "🏾", n: "emoji modifier fitzpatrick type-5" },
    { e: "🏿", n: "emoji modifier fitzpatrick type-6" },
    { e: "🐀", n: "rat" },
    { e: "🐁", n: "mouse" },
    { e: "🐂", n: "ox" },
    { e: "🐃", n: "water buffalo" },
    { e: "🐄", n: "cow" },
    { e: "🐅", n: "tiger" },
    { e: "🐆", n: "leopard" },
    { e: "🐇", n: "rabbit" },
    { e: "🐈", n: "cat" },
    { e: "🐉", n: "dragon" },
    { e: "🐊", n: "crocodile" },
    { e: "🐋", n: "whale" },
    { e: "🐌", n: "snail" },
    { e: "🐍", n: "snake", k: "python snake" },
    { e: "🐎", n: "horse" },
    { e: "🐏", n: "ram" },
    { e: "🐐", n: "goat" },
    { e: "🐑", n: "sheep" },
    { e: "🐒", n: "monkey" },
    { e: "🐓", n: "rooster" },
    { e: "🐔", n: "chicken" },
    { e: "🐕", n: "dog" },
    { e: "🐖", n: "pig" },
    { e: "🐗", n: "boar" },
    { e: "🐘", n: "elephant" },
    { e: "🐙", n: "octopus" },
    { e: "🐚", n: "spiral shell" },
    { e: "🐛", n: "bug", k: "bug insect issue defect" },
    { e: "🐜", n: "ant" },
    { e: "🐝", n: "honeybee" },
    { e: "🐞", n: "lady beetle" },
    { e: "🐟", n: "fish" },
    { e: "🐠", n: "tropical fish" },
    { e: "🐡", n: "blowfish" },
    { e: "🐢", n: "turtle" },
    { e: "🐣", n: "hatching chick" },
    { e: "🐤", n: "baby chick" },
    { e: "🐥", n: "front-facing baby chick" },
    { e: "🐦", n: "bird" },
    { e: "🐧", n: "penguin", k: "linux tux penguin" },
    { e: "🐨", n: "koala" },
    { e: "🐩", n: "poodle" },
    { e: "🐪", n: "dromedary camel" },
    { e: "🐫", n: "bactrian camel" },
    { e: "🐬", n: "dolphin" },
    { e: "🐭", n: "mouse face" },
    { e: "🐮", n: "cow face" },
    { e: "🐯", n: "tiger face" },
    { e: "🐰", n: "rabbit face" },
    { e: "🐱", n: "cat face" },
    { e: "🐲", n: "dragon face" },
    { e: "🐳", n: "spouting whale" },
    { e: "🐴", n: "horse face" },
    { e: "🐵", n: "monkey face" },
    { e: "🐶", n: "dog face" },
    { e: "🐷", n: "pig face" },
    { e: "🐸", n: "frog face" },
    { e: "🐹", n: "hamster face" },
    { e: "🐺", n: "wolf face" },
    { e: "🐻", n: "bear face" },
    { e: "🐼", n: "panda face" },
    { e: "🐽", n: "pig nose" },
    { e: "🐾", n: "paw prints" },
    { e: "👀", n: "eyes", k: "look watching eyes" },
    { e: "👂", n: "ear" },
    { e: "👃", n: "nose" },
    { e: "👄", n: "mouth" },
    { e: "👅", n: "tongue" },
    { e: "👆", n: "white up pointing backhand index" },
    { e: "👇", n: "white down pointing backhand index" },
    { e: "👈", n: "white left pointing backhand index" },
    { e: "👉", n: "white right pointing backhand index" },
    { e: "👊", n: "fisted hand sign" },
    { e: "👋", n: "waving hand sign" },
    { e: "👌", n: "ok hand sign", k: "ok perfect okhand" },
    { e: "👍", n: "thumbs up sign", k: "ok yes approve like thumbsup good" },
    { e: "👎", n: "thumbs down sign", k: "no reject dislike thumbsdown bad" },
    { e: "👏", n: "clapping hands sign", k: "applause bravo clap" },
    { e: "👐", n: "open hands sign" },
    { e: "👑", n: "crown" },
    { e: "👒", n: "womans hat" },
    { e: "👓", n: "eyeglasses" },
    { e: "👔", n: "necktie" },
    { e: "👕", n: "t-shirt" },
    { e: "👖", n: "jeans" },
    { e: "👗", n: "dress" },
    { e: "👘", n: "kimono" },
    { e: "👙", n: "bikini" },
    { e: "👚", n: "womans clothes" },
    { e: "👛", n: "purse" },
    { e: "👜", n: "handbag" },
    { e: "👝", n: "pouch" },
    { e: "👞", n: "mans shoe" },
    { e: "👟", n: "athletic shoe" },
    { e: "👠", n: "high-heeled shoe" },
    { e: "👡", n: "womans sandal" },
    { e: "👢", n: "womans boots" },
    { e: "👣", n: "footprints" },
    { e: "👤", n: "bust in silhouette" },
    { e: "👥", n: "busts in silhouette" },
    { e: "👦", n: "boy" },
    { e: "👧", n: "girl" },
    { e: "👨", n: "man" },
    { e: "👩", n: "woman" },
    { e: "👪", n: "family" },
    { e: "👫", n: "man and woman holding hands" },
    { e: "👬", n: "two men holding hands" },
    { e: "👭", n: "two women holding hands" },
    { e: "👮", n: "police officer" },
    { e: "👯", n: "woman with bunny ears" },
    { e: "👰", n: "bride with veil" },
    { e: "👱", n: "person with blond hair" },
    { e: "👲", n: "man with gua pi mao" },
    { e: "👳", n: "man with turban" },
    { e: "👴", n: "older man" },
    { e: "👵", n: "older woman" },
    { e: "👶", n: "baby" },
    { e: "👷", n: "construction worker" },
    { e: "👸", n: "princess" },
    { e: "👹", n: "japanese ogre" },
    { e: "👺", n: "japanese goblin" },
    { e: "👻", n: "ghost", k: "ghost spooky" },
    { e: "👼", n: "baby angel" },
    { e: "👽", n: "extraterrestrial alien" },
    { e: "👾", n: "alien monster" },
    { e: "👿", n: "imp" },
    { e: "💀", n: "skull", k: "skull dead" },
    { e: "💁", n: "information desk person" },
    { e: "💂", n: "guardsman" },
    { e: "💃", n: "dancer" },
    { e: "💄", n: "lipstick" },
    { e: "💅", n: "nail polish" },
    { e: "💆", n: "face massage" },
    { e: "💇", n: "haircut" },
    { e: "💈", n: "barber pole" },
    { e: "💉", n: "syringe" },
    { e: "💊", n: "pill" },
    { e: "💋", n: "kiss mark" },
    { e: "💌", n: "love letter" },
    { e: "💍", n: "ring" },
    { e: "💎", n: "gem stone" },
    { e: "💏", n: "kiss" },
    { e: "💐", n: "bouquet" },
    { e: "💑", n: "couple with heart" },
    { e: "💒", n: "wedding" },
    { e: "💓", n: "beating heart" },
    { e: "💔", n: "broken heart", k: "broken heart sad" },
    { e: "💕", n: "two hearts" },
    { e: "💖", n: "sparkling heart" },
    { e: "💗", n: "growing heart" },
    { e: "💘", n: "heart with arrow" },
    { e: "💙", n: "blue heart" },
    { e: "💚", n: "green heart" },
    { e: "💛", n: "yellow heart" },
    { e: "💜", n: "purple heart" },
    { e: "💝", n: "heart with ribbon" },
    { e: "💞", n: "revolving hearts" },
    { e: "💟", n: "heart decoration" },
    { e: "💠", n: "diamond shape with a dot inside" },
    { e: "💡", n: "electric light bulb", k: "idea lightbulb tip" },
    { e: "💢", n: "anger symbol" },
    { e: "💣", n: "bomb" },
    { e: "💤", n: "sleeping symbol" },
    { e: "💥", n: "collision symbol" },
    { e: "💦", n: "splashing sweat symbol" },
    { e: "💧", n: "droplet" },
    { e: "💨", n: "dash symbol" },
    { e: "💩", n: "pile of poo" },
    { e: "💪", n: "flexed biceps", k: "strong muscle" },
    { e: "💫", n: "dizzy symbol" },
    { e: "💬", n: "speech balloon" },
    { e: "💭", n: "thought balloon" },
    { e: "💮", n: "white flower" },
    { e: "💯", n: "hundred points symbol", k: "100 perfect hundred" },
    { e: "💰", n: "money bag" },
    { e: "💱", n: "currency exchange" },
    { e: "💲", n: "heavy dollar sign" },
    { e: "💳", n: "credit card" },
    { e: "💴", n: "banknote with yen sign" },
    { e: "💵", n: "banknote with dollar sign" },
    { e: "💶", n: "banknote with euro sign" },
    { e: "💷", n: "banknote with pound sign" },
    { e: "💸", n: "money with wings" },
    { e: "💹", n: "chart with upwards trend and yen sign" },
    { e: "💺", n: "seat" },
    { e: "💻", n: "personal computer" },
    { e: "💼", n: "briefcase" },
    { e: "💽", n: "minidisc" },
    { e: "💾", n: "floppy disk", k: "save disk floppy" },
    { e: "💿", n: "optical disc" },
    { e: "📀", n: "dvd" },
    { e: "📁", n: "file folder" },
    { e: "📂", n: "open file folder" },
    { e: "📃", n: "page with curl" },
    { e: "📄", n: "page facing up" },
    { e: "📅", n: "calendar" },
    { e: "📆", n: "tear-off calendar" },
    { e: "📇", n: "card index" },
    { e: "📈", n: "chart with upwards trend", k: "growth up graph chart" },
    { e: "📉", n: "chart with downwards trend", k: "down loss graph chart" },
    { e: "📊", n: "bar chart" },
    { e: "📋", n: "clipboard" },
    { e: "📌", n: "pushpin", k: "pin" },
    { e: "📍", n: "round pushpin" },
    { e: "📎", n: "paperclip" },
    { e: "📏", n: "straight ruler" },
    { e: "📐", n: "triangular ruler" },
    { e: "📑", n: "bookmark tabs" },
    { e: "📒", n: "ledger" },
    { e: "📓", n: "notebook" },
    { e: "📔", n: "notebook with decorative cover" },
    { e: "📕", n: "closed book" },
    { e: "📖", n: "open book" },
    { e: "📗", n: "green book" },
    { e: "📘", n: "blue book" },
    { e: "📙", n: "orange book" },
    { e: "📚", n: "books" },
    { e: "📛", n: "name badge" },
    { e: "📜", n: "scroll" },
    { e: "📝", n: "memo", k: "note write memo" },
    { e: "📞", n: "telephone receiver" },
    { e: "📟", n: "pager" },
    { e: "📠", n: "fax machine" },
    { e: "📡", n: "satellite antenna" },
    { e: "📢", n: "public address loudspeaker" },
    { e: "📣", n: "cheering megaphone" },
    { e: "📤", n: "outbox tray" },
    { e: "📥", n: "inbox tray" },
    { e: "📦", n: "package", k: "box parcel package shipping" },
    { e: "📧", n: "e-mail symbol" },
    { e: "📨", n: "incoming envelope" },
    { e: "📩", n: "envelope with downwards arrow above" },
    { e: "📪", n: "closed mailbox with lowered flag" },
    { e: "📫", n: "closed mailbox with raised flag" },
    { e: "📬", n: "open mailbox with raised flag" },
    { e: "📭", n: "open mailbox with lowered flag" },
    { e: "📮", n: "postbox" },
    { e: "📯", n: "postal horn" },
    { e: "📰", n: "newspaper" },
    { e: "📱", n: "mobile phone" },
    { e: "📲", n: "mobile phone with rightwards arrow at left" },
    { e: "📳", n: "vibration mode" },
    { e: "📴", n: "mobile phone off" },
    { e: "📵", n: "no mobile phones" },
    { e: "📶", n: "antenna with bars" },
    { e: "📷", n: "camera" },
    { e: "📸", n: "camera with flash" },
    { e: "📹", n: "video camera" },
    { e: "📺", n: "television" },
    { e: "📻", n: "radio" },
    { e: "📼", n: "videocassette" },
    { e: "📿", n: "prayer beads" },
    { e: "🔀", n: "twisted rightwards arrows" },
    { e: "🔁", n: "clockwise rightwards and leftwards open circle arrows" },
    { e: "🔂", n: "clockwise rightwards and leftwards open circle arrows with circled one overlay" },
    { e: "🔃", n: "clockwise downwards and upwards open circle arrows" },
    { e: "🔄", n: "anticlockwise downwards and upwards open circle arrows" },
    { e: "🔅", n: "low brightness symbol" },
    { e: "🔆", n: "high brightness symbol" },
    { e: "🔇", n: "speaker with cancellation stroke" },
    { e: "🔈", n: "speaker" },
    { e: "🔉", n: "speaker with one sound wave" },
    { e: "🔊", n: "speaker with three sound waves" },
    { e: "🔋", n: "battery" },
    { e: "🔌", n: "electric plug" },
    { e: "🔍", n: "left-pointing magnifying glass", k: "search find magnify" },
    { e: "🔎", n: "right-pointing magnifying glass" },
    { e: "🔏", n: "lock with ink pen" },
    { e: "🔐", n: "closed lock with key" },
    { e: "🔑", n: "key" },
    { e: "🔒", n: "lock", k: "lock secure private" },
    { e: "🔓", n: "open lock", k: "unlock open" },
    { e: "🔔", n: "bell" },
    { e: "🔕", n: "bell with cancellation stroke" },
    { e: "🔖", n: "bookmark" },
    { e: "🔗", n: "link symbol" },
    { e: "🔘", n: "radio button" },
    { e: "🔙", n: "back with leftwards arrow above" },
    { e: "🔚", n: "end with leftwards arrow above" },
    { e: "🔛", n: "on with exclamation mark with left right arrow above" },
    { e: "🔜", n: "soon with rightwards arrow above" },
    { e: "🔝", n: "top with upwards arrow above" },
    { e: "🔞", n: "no one under eighteen symbol" },
    { e: "🔟", n: "keycap ten" },
    { e: "🔠", n: "input symbol for latin capital letters" },
    { e: "🔡", n: "input symbol for latin small letters" },
    { e: "🔢", n: "input symbol for numbers" },
    { e: "🔣", n: "input symbol for symbols" },
    { e: "🔤", n: "input symbol for latin letters" },
    { e: "🔥", n: "fire", k: "lit hot flame fire" },
    { e: "🔦", n: "electric torch" },
    { e: "🔧", n: "wrench", k: "fix tool wrench" },
    { e: "🔨", n: "hammer", k: "build tool hammer" },
    { e: "🔩", n: "nut and bolt" },
    { e: "🔪", n: "hocho" },
    { e: "🔫", n: "pistol" },
    { e: "🔬", n: "microscope" },
    { e: "🔭", n: "telescope" },
    { e: "🔮", n: "crystal ball" },
    { e: "🔯", n: "six pointed star with middle dot" },
    { e: "🔰", n: "japanese symbol for beginner" },
    { e: "🔱", n: "trident emblem" },
    { e: "🔲", n: "black square button" },
    { e: "🔳", n: "white square button" },
    { e: "🔴", n: "large red circle" },
    { e: "🔵", n: "large blue circle" },
    { e: "🔶", n: "large orange diamond" },
    { e: "🔷", n: "large blue diamond" },
    { e: "🔸", n: "small orange diamond" },
    { e: "🔹", n: "small blue diamond" },
    { e: "🔺", n: "up-pointing red triangle" },
    { e: "🔻", n: "down-pointing red triangle" },
    { e: "🔼", n: "up-pointing small red triangle" },
    { e: "🔽", n: "down-pointing small red triangle" },
    { e: "🕋", n: "kaaba" },
    { e: "🕌", n: "mosque" },
    { e: "🕍", n: "synagogue" },
    { e: "🕎", n: "menorah with nine branches" },
    { e: "🕐", n: "clock face one oclock" },
    { e: "🕑", n: "clock face two oclock" },
    { e: "🕒", n: "clock face three oclock" },
    { e: "🕓", n: "clock face four oclock" },
    { e: "🕔", n: "clock face five oclock" },
    { e: "🕕", n: "clock face six oclock" },
    { e: "🕖", n: "clock face seven oclock" },
    { e: "🕗", n: "clock face eight oclock" },
    { e: "🕘", n: "clock face nine oclock" },
    { e: "🕙", n: "clock face ten oclock" },
    { e: "🕚", n: "clock face eleven oclock" },
    { e: "🕛", n: "clock face twelve oclock" },
    { e: "🕜", n: "clock face one-thirty" },
    { e: "🕝", n: "clock face two-thirty" },
    { e: "🕞", n: "clock face three-thirty" },
    { e: "🕟", n: "clock face four-thirty" },
    { e: "🕠", n: "clock face five-thirty" },
    { e: "🕡", n: "clock face six-thirty" },
    { e: "🕢", n: "clock face seven-thirty" },
    { e: "🕣", n: "clock face eight-thirty" },
    { e: "🕤", n: "clock face nine-thirty" },
    { e: "🕥", n: "clock face ten-thirty" },
    { e: "🕦", n: "clock face eleven-thirty" },
    { e: "🕧", n: "clock face twelve-thirty" },
    { e: "🕺", n: "man dancing" },
    { e: "🖕", n: "reversed hand with middle finger extended" },
    { e: "🖖", n: "raised hand with part between middle and ring fingers" },
    { e: "🖤", n: "black heart" },
    { e: "🗻", n: "mount fuji" },
    { e: "🗼", n: "tokyo tower" },
    { e: "🗽", n: "statue of liberty" },
    { e: "🗾", n: "silhouette of japan" },
    { e: "🗿", n: "moyai" },
    { e: "😀", n: "grinning face", k: "smile happy grin" },
    { e: "😁", n: "grinning face with smiling eyes" },
    { e: "😂", n: "face with tears of joy", k: "lol laugh cry funny tears" },
    { e: "😃", n: "smiling face with open mouth", k: "smile happy" },
    { e: "😄", n: "smiling face with open mouth and smiling eyes", k: "smile happy" },
    { e: "😅", n: "smiling face with open mouth and cold sweat", k: "sweat nervous" },
    { e: "😆", n: "smiling face with open mouth and tightly-closed eyes" },
    { e: "😇", n: "smiling face with halo" },
    { e: "😈", n: "smiling face with horns" },
    { e: "😉", n: "winking face", k: "wink" },
    { e: "😊", n: "smiling face with smiling eyes" },
    { e: "😋", n: "face savouring delicious food" },
    { e: "😌", n: "relieved face" },
    { e: "😍", n: "smiling face with heart-shaped eyes", k: "love heart eyes" },
    { e: "😎", n: "smiling face with sunglasses", k: "cool sunglasses" },
    { e: "😏", n: "smirking face" },
    { e: "😐", n: "neutral face" },
    { e: "😑", n: "expressionless face" },
    { e: "😒", n: "unamused face" },
    { e: "😓", n: "face with cold sweat" },
    { e: "😔", n: "pensive face" },
    { e: "😕", n: "confused face" },
    { e: "😖", n: "confounded face" },
    { e: "😗", n: "kissing face" },
    { e: "😘", n: "face throwing a kiss" },
    { e: "😙", n: "kissing face with smiling eyes" },
    { e: "😚", n: "kissing face with closed eyes" },
    { e: "😛", n: "face with stuck-out tongue" },
    { e: "😜", n: "face with stuck-out tongue and winking eye" },
    { e: "😝", n: "face with stuck-out tongue and tightly-closed eyes" },
    { e: "😞", n: "disappointed face" },
    { e: "😟", n: "worried face" },
    { e: "😠", n: "angry face" },
    { e: "😡", n: "pouting face" },
    { e: "😢", n: "crying face" },
    { e: "😣", n: "persevering face" },
    { e: "😤", n: "face with look of triumph" },
    { e: "😥", n: "disappointed but relieved face" },
    { e: "😦", n: "frowning face with open mouth" },
    { e: "😧", n: "anguished face" },
    { e: "😨", n: "fearful face" },
    { e: "😩", n: "weary face" },
    { e: "😪", n: "sleepy face" },
    { e: "😫", n: "tired face" },
    { e: "😬", n: "grimacing face", k: "grimace awkward" },
    { e: "😭", n: "loudly crying face", k: "sob cry sad" },
    { e: "😮", n: "face with open mouth" },
    { e: "😯", n: "hushed face" },
    { e: "😰", n: "face with open mouth and cold sweat" },
    { e: "😱", n: "face screaming in fear" },
    { e: "😲", n: "astonished face" },
    { e: "😳", n: "flushed face" },
    { e: "😴", n: "sleeping face", k: "sleep tired zzz" },
    { e: "😵", n: "dizzy face" },
    { e: "😶", n: "face without mouth" },
    { e: "😷", n: "face with medical mask" },
    { e: "😸", n: "grinning cat face with smiling eyes" },
    { e: "😹", n: "cat face with tears of joy" },
    { e: "😺", n: "smiling cat face with open mouth" },
    { e: "😻", n: "smiling cat face with heart-shaped eyes" },
    { e: "😼", n: "cat face with wry smile" },
    { e: "😽", n: "kissing cat face with closed eyes" },
    { e: "😾", n: "pouting cat face" },
    { e: "😿", n: "crying cat face" },
    { e: "🙀", n: "weary cat face" },
    { e: "🙁", n: "slightly frowning face" },
    { e: "🙂", n: "slightly smiling face" },
    { e: "🙃", n: "upside-down face", k: "upside down irony" },
    { e: "🙄", n: "face with rolling eyes", k: "annoyed whatever eyeroll" },
    { e: "🙅", n: "face with no good gesture" },
    { e: "🙆", n: "face with ok gesture" },
    { e: "🙇", n: "person bowing deeply" },
    { e: "🙈", n: "see-no-evil monkey" },
    { e: "🙉", n: "hear-no-evil monkey" },
    { e: "🙊", n: "speak-no-evil monkey" },
    { e: "🙋", n: "happy person raising one hand" },
    { e: "🙌", n: "person raising both hands in celebration", k: "yay celebrate hooray" },
    { e: "🙍", n: "person frowning" },
    { e: "🙎", n: "person with pouting face" },
    { e: "🙏", n: "person with folded hands", k: "please thanks pray" },
    { e: "🚀", n: "rocket", k: "launch ship deploy fast rocket" },
    { e: "🚁", n: "helicopter" },
    { e: "🚂", n: "steam locomotive" },
    { e: "🚃", n: "railway car" },
    { e: "🚄", n: "high-speed train" },
    { e: "🚅", n: "high-speed train with bullet nose" },
    { e: "🚆", n: "train" },
    { e: "🚇", n: "metro" },
    { e: "🚈", n: "light rail" },
    { e: "🚉", n: "station" },
    { e: "🚊", n: "tram" },
    { e: "🚋", n: "tram car" },
    { e: "🚌", n: "bus" },
    { e: "🚍", n: "oncoming bus" },
    { e: "🚎", n: "trolleybus" },
    { e: "🚏", n: "bus stop" },
    { e: "🚐", n: "minibus" },
    { e: "🚑", n: "ambulance" },
    { e: "🚒", n: "fire engine" },
    { e: "🚓", n: "police car" },
    { e: "🚔", n: "oncoming police car" },
    { e: "🚕", n: "taxi" },
    { e: "🚖", n: "oncoming taxi" },
    { e: "🚗", n: "automobile" },
    { e: "🚘", n: "oncoming automobile" },
    { e: "🚙", n: "recreational vehicle" },
    { e: "🚚", n: "delivery truck" },
    { e: "🚛", n: "articulated lorry" },
    { e: "🚜", n: "tractor" },
    { e: "🚝", n: "monorail" },
    { e: "🚞", n: "mountain railway" },
    { e: "🚟", n: "suspension railway" },
    { e: "🚠", n: "mountain cableway" },
    { e: "🚡", n: "aerial tramway" },
    { e: "🚢", n: "ship" },
    { e: "🚣", n: "rowboat" },
    { e: "🚤", n: "speedboat" },
    { e: "🚥", n: "horizontal traffic light" },
    { e: "🚦", n: "vertical traffic light" },
    { e: "🚧", n: "construction sign" },
    { e: "🚨", n: "police cars revolving light" },
    { e: "🚩", n: "triangular flag on post" },
    { e: "🚪", n: "door" },
    { e: "🚫", n: "no entry sign" },
    { e: "🚬", n: "smoking symbol" },
    { e: "🚭", n: "no smoking symbol" },
    { e: "🚮", n: "put litter in its place symbol" },
    { e: "🚯", n: "do not litter symbol" },
    { e: "🚰", n: "potable water symbol" },
    { e: "🚱", n: "non-potable water symbol" },
    { e: "🚲", n: "bicycle" },
    { e: "🚳", n: "no bicycles" },
    { e: "🚴", n: "bicyclist" },
    { e: "🚵", n: "mountain bicyclist" },
    { e: "🚶", n: "pedestrian" },
    { e: "🚷", n: "no pedestrians" },
    { e: "🚸", n: "children crossing" },
    { e: "🚹", n: "mens symbol" },
    { e: "🚺", n: "womens symbol" },
    { e: "🚻", n: "restroom" },
    { e: "🚼", n: "baby symbol" },
    { e: "🚽", n: "toilet" },
    { e: "🚾", n: "water closet" },
    { e: "🚿", n: "shower" },
    { e: "🛀", n: "bath" },
    { e: "🛁", n: "bathtub" },
    { e: "🛂", n: "passport control" },
    { e: "🛃", n: "customs" },
    { e: "🛄", n: "baggage claim" },
    { e: "🛅", n: "left luggage" },
    { e: "🛌", n: "sleeping accommodation" },
    { e: "🛐", n: "place of worship" },
    { e: "🛑", n: "octagonal sign" },
    { e: "🛒", n: "shopping trolley" },
    { e: "🛕", n: "hindu temple" },
    { e: "🛖", n: "hut" },
    { e: "🛗", n: "elevator" },
    { e: "🛜", n: "wireless" },
    { e: "🛝", n: "playground slide" },
    { e: "🛞", n: "wheel" },
    { e: "🛟", n: "ring buoy" },
    { e: "🛫", n: "airplane departure" },
    { e: "🛬", n: "airplane arriving" },
    { e: "🛴", n: "scooter" },
    { e: "🛵", n: "motor scooter" },
    { e: "🛶", n: "canoe" },
    { e: "🛷", n: "sled" },
    { e: "🛸", n: "flying saucer" },
    { e: "🛹", n: "skateboard" },
    { e: "🛺", n: "auto rickshaw" },
    { e: "🛻", n: "pickup truck" },
    { e: "🛼", n: "roller skate" },
    { e: "🤌", n: "pinched fingers" },
    { e: "🤍", n: "white heart" },
    { e: "🤎", n: "brown heart" },
    { e: "🤏", n: "pinching hand" },
    { e: "🤐", n: "zipper-mouth face" },
    { e: "🤑", n: "money-mouth face" },
    { e: "🤒", n: "face with thermometer" },
    { e: "🤓", n: "nerd face" },
    { e: "🤔", n: "thinking face", k: "think hmm" },
    { e: "🤕", n: "face with head-bandage" },
    { e: "🤖", n: "robot face", k: "bot robot ai" },
    { e: "🤗", n: "hugging face" },
    { e: "🤘", n: "sign of the horns" },
    { e: "🤙", n: "call me hand" },
    { e: "🤚", n: "raised back of hand" },
    { e: "🤛", n: "left-facing fist" },
    { e: "🤜", n: "right-facing fist" },
    { e: "🤝", n: "handshake", k: "deal agree handshake" },
    { e: "🤞", n: "hand with index and middle fingers crossed" },
    { e: "🤟", n: "i love you hand sign" },
    { e: "🤠", n: "face with cowboy hat" },
    { e: "🤡", n: "clown face" },
    { e: "🤢", n: "nauseated face" },
    { e: "🤣", n: "rolling on the floor laughing", k: "lol rofl funny" },
    { e: "🤤", n: "drooling face" },
    { e: "🤥", n: "lying face" },
    { e: "🤦", n: "face palm" },
    { e: "🤧", n: "sneezing face" },
    { e: "🤨", n: "face with one eyebrow raised" },
    { e: "🤩", n: "grinning face with star eyes" },
    { e: "🤪", n: "grinning face with one large and one small eye" },
    { e: "🤫", n: "face with finger covering closed lips" },
    { e: "🤬", n: "serious face with symbols covering mouth" },
    { e: "🤭", n: "smiling face with smiling eyes and hand covering mouth" },
    { e: "🤮", n: "face with open mouth vomiting" },
    { e: "🤯", n: "shocked face with exploding head", k: "mindblown wow" },
    { e: "🤰", n: "pregnant woman" },
    { e: "🤱", n: "breast-feeding" },
    { e: "🤲", n: "palms up together" },
    { e: "🤳", n: "selfie" },
    { e: "🤴", n: "prince" },
    { e: "🤵", n: "man in tuxedo" },
    { e: "🤶", n: "mother christmas" },
    { e: "🤷", n: "shrug" },
    { e: "🤸", n: "person doing cartwheel" },
    { e: "🤹", n: "juggling" },
    { e: "🤺", n: "fencer" },
    { e: "🤼", n: "wrestlers" },
    { e: "🤽", n: "water polo" },
    { e: "🤾", n: "handball" },
    { e: "🤿", n: "diving mask" },
    { e: "🥀", n: "wilted flower" },
    { e: "🥁", n: "drum with drumsticks" },
    { e: "🥂", n: "clinking glasses" },
    { e: "🥃", n: "tumbler glass" },
    { e: "🥄", n: "spoon" },
    { e: "🥅", n: "goal net" },
    { e: "🥇", n: "first place medal" },
    { e: "🥈", n: "second place medal" },
    { e: "🥉", n: "third place medal" },
    { e: "🥊", n: "boxing glove" },
    { e: "🥋", n: "martial arts uniform" },
    { e: "🥌", n: "curling stone" },
    { e: "🥍", n: "lacrosse stick and ball" },
    { e: "🥎", n: "softball" },
    { e: "🥏", n: "flying disc" },
    { e: "🥐", n: "croissant" },
    { e: "🥑", n: "avocado" },
    { e: "🥒", n: "cucumber" },
    { e: "🥓", n: "bacon" },
    { e: "🥔", n: "potato" },
    { e: "🥕", n: "carrot" },
    { e: "🥖", n: "baguette bread" },
    { e: "🥗", n: "green salad" },
    { e: "🥘", n: "shallow pan of food" },
    { e: "🥙", n: "stuffed flatbread" },
    { e: "🥚", n: "egg" },
    { e: "🥛", n: "glass of milk" },
    { e: "🥜", n: "peanuts" },
    { e: "🥝", n: "kiwifruit" },
    { e: "🥞", n: "pancakes" },
    { e: "🥟", n: "dumpling" },
    { e: "🥠", n: "fortune cookie" },
    { e: "🥡", n: "takeout box" },
    { e: "🥢", n: "chopsticks" },
    { e: "🥣", n: "bowl with spoon" },
    { e: "🥤", n: "cup with straw" },
    { e: "🥥", n: "coconut" },
    { e: "🥦", n: "broccoli" },
    { e: "🥧", n: "pie" },
    { e: "🥨", n: "pretzel" },
    { e: "🥩", n: "cut of meat" },
    { e: "🥪", n: "sandwich" },
    { e: "🥫", n: "canned food" },
    { e: "🥬", n: "leafy green" },
    { e: "🥭", n: "mango" },
    { e: "🥮", n: "moon cake" },
    { e: "🥯", n: "bagel" },
    { e: "🥰", n: "smiling face with smiling eyes and three hearts", k: "love affection" },
    { e: "🥱", n: "yawning face" },
    { e: "🥲", n: "smiling face with tear" },
    { e: "🥳", n: "face with party horn and party hat", k: "party celebrate" },
    { e: "🥴", n: "face with uneven eyes and wavy mouth" },
    { e: "🥵", n: "overheated face" },
    { e: "🥶", n: "freezing face" },
    { e: "🥷", n: "ninja" },
    { e: "🥸", n: "disguised face" },
    { e: "🥹", n: "face holding back tears" },
    { e: "🥺", n: "face with pleading eyes" },
    { e: "🥻", n: "sari" },
    { e: "🥼", n: "lab coat" },
    { e: "🥽", n: "goggles" },
    { e: "🥾", n: "hiking boot" },
    { e: "🥿", n: "flat shoe" },
    { e: "🦀", n: "crab" },
    { e: "🦁", n: "lion face" },
    { e: "🦂", n: "scorpion" },
    { e: "🦃", n: "turkey" },
    { e: "🦄", n: "unicorn face" },
    { e: "🦅", n: "eagle" },
    { e: "🦆", n: "duck" },
    { e: "🦇", n: "bat" },
    { e: "🦈", n: "shark" },
    { e: "🦉", n: "owl" },
    { e: "🦊", n: "fox face" },
    { e: "🦋", n: "butterfly" },
    { e: "🦌", n: "deer" },
    { e: "🦍", n: "gorilla" },
    { e: "🦎", n: "lizard" },
    { e: "🦏", n: "rhinoceros" },
    { e: "🦐", n: "shrimp" },
    { e: "🦑", n: "squid" },
    { e: "🦒", n: "giraffe face" },
    { e: "🦓", n: "zebra face" },
    { e: "🦔", n: "hedgehog" },
    { e: "🦕", n: "sauropod" },
    { e: "🦖", n: "t-rex" },
    { e: "🦗", n: "cricket" },
    { e: "🦘", n: "kangaroo" },
    { e: "🦙", n: "llama" },
    { e: "🦚", n: "peacock" },
    { e: "🦛", n: "hippopotamus" },
    { e: "🦜", n: "parrot" },
    { e: "🦝", n: "raccoon" },
    { e: "🦞", n: "lobster" },
    { e: "🦟", n: "mosquito" },
    { e: "🦠", n: "microbe" },
    { e: "🦡", n: "badger" },
    { e: "🦢", n: "swan" },
    { e: "🦣", n: "mammoth" },
    { e: "🦤", n: "dodo" },
    { e: "🦥", n: "sloth" },
    { e: "🦦", n: "otter" },
    { e: "🦧", n: "orangutan" },
    { e: "🦨", n: "skunk" },
    { e: "🦩", n: "flamingo" },
    { e: "🦪", n: "oyster" },
    { e: "🦫", n: "beaver" },
    { e: "🦬", n: "bison" },
    { e: "🦭", n: "seal" },
    { e: "🦮", n: "guide dog" },
    { e: "🦯", n: "probing cane" },
    { e: "🦰", n: "emoji component red hair" },
    { e: "🦱", n: "emoji component curly hair" },
    { e: "🦲", n: "emoji component bald" },
    { e: "🦳", n: "emoji component white hair" },
    { e: "🦴", n: "bone" },
    { e: "🦵", n: "leg" },
    { e: "🦶", n: "foot" },
    { e: "🦷", n: "tooth" },
    { e: "🦸", n: "superhero" },
    { e: "🦹", n: "supervillain" },
    { e: "🦺", n: "safety vest" },
    { e: "🦻", n: "ear with hearing aid" },
    { e: "🦼", n: "motorized wheelchair" },
    { e: "🦽", n: "manual wheelchair" },
    { e: "🦾", n: "mechanical arm" },
    { e: "🦿", n: "mechanical leg" },
    { e: "🧀", n: "cheese wedge" },
    { e: "🧁", n: "cupcake" },
    { e: "🧂", n: "salt shaker" },
    { e: "🧃", n: "beverage box" },
    { e: "🧄", n: "garlic" },
    { e: "🧅", n: "onion" },
    { e: "🧆", n: "falafel" },
    { e: "🧇", n: "waffle" },
    { e: "🧈", n: "butter" },
    { e: "🧉", n: "mate drink" },
    { e: "🧊", n: "ice cube" },
    { e: "🧋", n: "bubble tea" },
    { e: "🧌", n: "troll" },
    { e: "🧍", n: "standing person" },
    { e: "🧎", n: "kneeling person" },
    { e: "🧏", n: "deaf person" },
    { e: "🧐", n: "face with monocle" },
    { e: "🧑", n: "adult" },
    { e: "🧒", n: "child" },
    { e: "🧓", n: "older adult" },
    { e: "🧔", n: "bearded person" },
    { e: "🧕", n: "person with headscarf" },
    { e: "🧖", n: "person in steamy room" },
    { e: "🧗", n: "person climbing" },
    { e: "🧘", n: "person in lotus position" },
    { e: "🧙", n: "mage" },
    { e: "🧚", n: "fairy" },
    { e: "🧛", n: "vampire" },
    { e: "🧜", n: "merperson" },
    { e: "🧝", n: "elf" },
    { e: "🧞", n: "genie" },
    { e: "🧟", n: "zombie" },
    { e: "🧠", n: "brain", k: "brain smart mind" },
    { e: "🧡", n: "orange heart" },
    { e: "🧢", n: "billed cap" },
    { e: "🧣", n: "scarf" },
    { e: "🧤", n: "gloves" },
    { e: "🧥", n: "coat" },
    { e: "🧦", n: "socks" },
    { e: "🧧", n: "red gift envelope" },
    { e: "🧨", n: "firecracker" },
    { e: "🧩", n: "jigsaw puzzle piece" },
    { e: "🧪", n: "test tube" },
    { e: "🧫", n: "petri dish" },
    { e: "🧬", n: "dna double helix" },
    { e: "🧭", n: "compass" },
    { e: "🧮", n: "abacus" },
    { e: "🧯", n: "fire extinguisher" },
    { e: "🧰", n: "toolbox" },
    { e: "🧱", n: "brick" },
    { e: "🧲", n: "magnet" },
    { e: "🧳", n: "luggage" },
    { e: "🧴", n: "lotion bottle" },
    { e: "🧵", n: "spool of thread" },
    { e: "🧶", n: "ball of yarn" },
    { e: "🧷", n: "safety pin" },
    { e: "🧸", n: "teddy bear" },
    { e: "🧹", n: "broom" },
    { e: "🧺", n: "basket" },
    { e: "🧻", n: "roll of paper" },
    { e: "🧼", n: "bar of soap" },
    { e: "🧽", n: "sponge" },
    { e: "🧾", n: "receipt" },
    { e: "🧿", n: "nazar amulet" },
    { e: "🩰", n: "ballet shoes" },
    { e: "🩱", n: "one-piece swimsuit" },
    { e: "🩲", n: "briefs" },
    { e: "🩳", n: "shorts" },
    { e: "🩴", n: "thong sandal" },
    { e: "🩵", n: "light blue heart" },
    { e: "🩶", n: "grey heart" },
    { e: "🩷", n: "pink heart" },
    { e: "🩸", n: "drop of blood" },
    { e: "🩹", n: "adhesive bandage" },
    { e: "🩺", n: "stethoscope" },
    { e: "🩻", n: "x-ray" },
    { e: "🩼", n: "crutch" },
    { e: "🪀", n: "yo-yo" },
    { e: "🪁", n: "kite" },
    { e: "🪂", n: "parachute" },
    { e: "🪃", n: "boomerang" },
    { e: "🪄", n: "magic wand" },
    { e: "🪅", n: "pinata" },
    { e: "🪆", n: "nesting dolls" },
    { e: "🪇", n: "maracas" },
    { e: "🪈", n: "flute" },
    { e: "🪉", n: "harp" },
    { e: "🪏", n: "shovel" },
    { e: "🪐", n: "ringed planet" },
    { e: "🪑", n: "chair" },
    { e: "🪒", n: "razor" },
    { e: "🪓", n: "axe" },
    { e: "🪔", n: "diya lamp" },
    { e: "🪕", n: "banjo" },
    { e: "🪖", n: "military helmet" },
    { e: "🪗", n: "accordion" },
    { e: "🪘", n: "long drum" },
    { e: "🪙", n: "coin" },
    { e: "🪚", n: "carpentry saw" },
    { e: "🪛", n: "screwdriver" },
    { e: "🪜", n: "ladder" },
    { e: "🪝", n: "hook" },
    { e: "🪞", n: "mirror" },
    { e: "🪟", n: "window" },
    { e: "🪠", n: "plunger" },
    { e: "🪡", n: "sewing needle" },
    { e: "🪢", n: "knot" },
    { e: "🪣", n: "bucket" },
    { e: "🪤", n: "mouse trap" },
    { e: "🪥", n: "toothbrush" },
    { e: "🪦", n: "headstone" },
    { e: "🪧", n: "placard" },
    { e: "🪨", n: "rock" },
    { e: "🪩", n: "mirror ball" },
    { e: "🪪", n: "identification card" },
    { e: "🪫", n: "low battery" },
    { e: "🪬", n: "hamsa" },
    { e: "🪭", n: "folding hand fan" },
    { e: "🪮", n: "hair pick" },
    { e: "🪯", n: "khanda" },
    { e: "🪰", n: "fly" },
    { e: "🪱", n: "worm" },
    { e: "🪲", n: "beetle" },
    { e: "🪳", n: "cockroach" },
    { e: "🪴", n: "potted plant" },
    { e: "🪵", n: "wood" },
    { e: "🪶", n: "feather" },
    { e: "🪷", n: "lotus" },
    { e: "🪸", n: "coral" },
    { e: "🪹", n: "empty nest" },
    { e: "🪺", n: "nest with eggs" },
    { e: "🪻", n: "hyacinth" },
    { e: "🪼", n: "jellyfish" },
    { e: "🪽", n: "wing" },
    { e: "🪾", n: "leafless tree" },
    { e: "🪿", n: "goose" },
    { e: "🫀", n: "anatomical heart" },
    { e: "🫁", n: "lungs" },
    { e: "🫂", n: "people hugging" },
    { e: "🫃", n: "pregnant man" },
    { e: "🫄", n: "pregnant person" },
    { e: "🫅", n: "person with crown" },
    { e: "🫆", n: "fingerprint" },
    { e: "🫎", n: "moose" },
    { e: "🫏", n: "donkey" },
    { e: "🫐", n: "blueberries" },
    { e: "🫑", n: "bell pepper" },
    { e: "🫒", n: "olive" },
    { e: "🫓", n: "flatbread" },
    { e: "🫔", n: "tamale" },
    { e: "🫕", n: "fondue" },
    { e: "🫖", n: "teapot" },
    { e: "🫗", n: "pouring liquid" },
    { e: "🫘", n: "beans" },
    { e: "🫙", n: "jar" },
    { e: "🫚", n: "ginger root" },
    { e: "🫛", n: "pea pod" },
    { e: "🫜", n: "root vegetable" },
    { e: "🫟", n: "splatter" },
    { e: "🫠", n: "melting face", k: "melt melting" },
    { e: "🫡", n: "saluting face" },
    { e: "🫢", n: "face with open eyes and hand over mouth" },
    { e: "🫣", n: "face with peeking eye" },
    { e: "🫤", n: "face with diagonal mouth" },
    { e: "🫥", n: "dotted line face" },
    { e: "🫦", n: "biting lip" },
    { e: "🫧", n: "bubbles" },
    { e: "🫨", n: "shaking face" },
    { e: "🫩", n: "face with bags under eyes" },
    { e: "🫰", n: "hand with index finger and thumb crossed" },
    { e: "🫱", n: "rightwards hand" },
    { e: "🫲", n: "leftwards hand" },
    { e: "🫳", n: "palm down hand" },
    { e: "🫴", n: "palm up hand" },
    { e: "🫵", n: "index pointing at the viewer" },
    { e: "🫶", n: "heart hands" },
    { e: "🫷", n: "leftwards pushing hand" },
    { e: "🫸", n: "rightwards pushing hand" },
    { e: "☔", n: "umbrella with rain drops" },
    { e: "☕", n: "hot beverage", k: "coffee caffeine hot" },
    { e: "♈", n: "aries" },
    { e: "♉", n: "taurus" },
    { e: "♊", n: "gemini" },
    { e: "♋", n: "cancer" },
    { e: "♌", n: "leo" },
    { e: "♍", n: "virgo" },
    { e: "♎", n: "libra" },
    { e: "♏", n: "scorpius" },
    { e: "♐", n: "sagittarius" },
    { e: "♑", n: "capricorn" },
    { e: "♒", n: "aquarius" },
    { e: "♓", n: "pisces" },
    { e: "♿", n: "wheelchair symbol" },
    { e: "⚓", n: "anchor" },
    { e: "⚡", n: "high voltage sign" },
    { e: "⚪", n: "medium white circle" },
    { e: "⚫", n: "medium black circle" },
    { e: "⚽", n: "soccer ball" },
    { e: "⚾", n: "baseball" },
    { e: "⛄", n: "snowman without snow" },
    { e: "⛅", n: "sun behind cloud" },
    { e: "⛎", n: "ophiuchus" },
    { e: "⛔", n: "no entry" },
    { e: "⛪", n: "church" },
    { e: "⛲", n: "fountain" },
    { e: "⛳", n: "flag in hole" },
    { e: "⛵", n: "sailboat" },
    { e: "⛺", n: "tent" },
    { e: "⛽", n: "fuel pump" },
    { e: "✅", n: "white heavy check mark", k: "done yes tick check ok" },
    { e: "✊", n: "raised fist" },
    { e: "✋", n: "raised hand" },
    { e: "✨", n: "sparkles", k: "shiny magic new sparkle" },
    { e: "❌", n: "cross mark", k: "no fail wrong x cross" },
    { e: "❎", n: "negative squared cross mark" },
    { e: "❓", n: "black question mark ornament" },
    { e: "❔", n: "white question mark ornament" },
    { e: "❕", n: "white exclamation mark ornament" },
    { e: "❗", n: "heavy exclamation mark symbol" },
    { e: "➕", n: "heavy plus sign" },
    { e: "➖", n: "heavy minus sign" },
    { e: "➗", n: "heavy division sign" },
    { e: "➰", n: "curly loop" },
    { e: "➿", n: "double curly loop" },
    { e: "⬛", n: "black large square" },
    { e: "⬜", n: "white large square" },
    { e: "⭐", n: "white medium star", k: "star favourite favorite" },
    { e: "⭕", n: "heavy large circle" },
];
